### ISSUE TITLE
Linked demo is missing style sheet.

### ISSUE THREAD

**Issue by tarnacious** [mtr/core-layout#19]
Hi,

The demo, https://mtr.github.io/core-layout/examples/#/, is rendered without style and displays the message "Errno::ENOENT: No such file or directory - ./src/examples/scss/style.scss".

I managed to get this working locally which is great as I was looking for a working example of angular-iscroll (which links to this demo in the readme)

Thanks

**Comment by mtr** [comment]
Thank you for the warning, @tarnacious.  I haven't had the time to look into this before now because of the holiday season, but now I'll look into this immediately.

**Comment by mtr** [comment]
I fixed an error in my `.gitignore` file that broke the gh-pages build.  The [demo](http://mtr.github.io/core-layout/examples/) should be working correctly again now.
